create table `restaurant`
(
	`restaurant_id` bigint(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`restaurant_name` varchar(255) NOT NULL DEFAULT '',
	`restaurant_contact` varchar(50) NOT NULL DEFAULT '',
	`restaurant_address` varchar(500) NOT NULL DEFAULT '',
	`restaurant_state` varchar(50) NOT NULL DEFAULT '',
	`restaurant_zip` varchar(5) NOT NULL DEFAULT '',
	`restaurant_title` varchar(50) NOT NULL DEFAULT '',
	`restaurant_description` varchar(500) NOT NULL DEFAULT '',
	`restaurant_business_day` varchar(500) NOT NULL DEFAULT '',
	`restaurant_business_hour` varchar(500) NOT NULL DEFAULT '',
	`restaurant_deliver_fee` decimal(18,2) NOT NULL DEFAULT 0.00,
	`restaurant_deliver_coverage` varchar(255) NOT NULL DEFAULT '',
	`restaurant_deliver_minimum_order` decimal(10,2) NOT NULL DEFAULT 0.00,
	`restaurant_deliver_time` time NOT NULL DEFAULT '00:00:00',
	`restaurant_image_path` varchar(500) NOT NULL DEFAULT '',
	`restaurant_rating` decimal(3,2) NOT NULL DEFAULT 0.00,
	`restaurant_rated_by` bigint(20) NOT NULL DEFAULT 0,
	`restaurant_status` varchar(50) NOT NULL DEFAULT '',
	`restaurant_life_status` varchar(50) NOT NULL DEFAULT '',
	`restaurant_balance` decimal(18,2) NOT NULL DEFAULT 0.00,
	`restaurant_cod` int(1) NOT NULL DEFAULT 0,
	`restaurant_owner_id` bigint(20) NOT NULL DEFAULT 0,
	`restaurant_created_by` bigint(20) NOT NULL DEFAULT 0,
	`restaurant_created_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`restaurant_updated_by` bigint(20) NOT NULL DEFAULT 0,
	`restaurant_updated_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
);